#define MICROPY_HW_BOARD_NAME "4MB/OTA SSL module"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_PY_BLUETOOTH                (0)
#define MICROPY_PY_BLUETOOTH_ENABLE_CENTRAL_MODE (0)
#define MICROPY_BLUETOOTH_NIMBLE            (0)
#define MICROPY_BLUETOOTH_NIMBLE_BINDINGS_ONLY (0)
#define MICROPY_SSL_MBEDTLS_3                    (0)
#define MICROPY_BOARD_FROZEN_BOOT_FILE "_app_boot.py"
#define MICROPY_GC_INITIAL_HEAP_SIZE (64 * 1024)


