module("aioctl.py", base_path="..", opt=3)
module("aioschedule.py", base_path="..", opt=3)
module("aiolog.py", base_path="..", opt=3)
module("aioclass.py", base_path="..", opt=3)
module("aioservice.py", base_path="..", opt=3)
module("app.py", base_path="../app", opt=3)
module("asyncmd_boot.py", base_path="../app", opt=3)
module("_app_boot.py", base_path="../app", opt=3)
module("aiostats.py", base_path="../tools", opt=3)
module("stats_service.py", base_path="../aioservices/services", opt=3)
module("watcher_service.py", base_path="../aioservices/services", opt=3)
module("service_logger.py", base_path="../tools/logging", opt=3)
module("filehandler.py", base_path="../tools/logging_handlers", opt=3)
module("dotenv.py", base_path="../tools/config", opt=3)
require("logging")
require("time")
