module("async_mip.py", base_path="../async_modules/async_mip", opt=3)
module("async_mqtt.py", base_path="../async_modules/async_mqtt", opt=3)
module("aioping.py", base_path="../async_modules/aioping")
module("mip_service.py", base_path="../aioservices/services")
module("network_service.py", base_path="../aioservices/services", opt=3)
module("aiomqtt_service.py", base_path="../aioservices/services")
module("wpa_supplicant_service.py", base_path="../aioservices/services", opt=3)
module("ping_service.py", base_path="../aioservices/services", opt=3)
module("ursyslogger.py", base_path="../tools/logging", opt=3)
module("rsysloghandler.py", base_path="../tools/logging_handlers", opt=3)
module("mqtt_cmdlib.py", base_path="../utils/aiomqtt_service", opt=3)
require("aiohttp")
require("ntptime")
